'''
В первой строке допущена ошибка, а во второй всё норм
print(3 + 5
print(Всё в порядке!)
'''
print(3 + 5)
print('Всё в порядке!')